sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: 
  - sudo apt-get install -qq g++-5

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

before_script: 
  - ./install_other_githubs.sh

script: 
  - ./build_desktop.sh

after_success: 
  - codecov
